services:
  fishy-rag:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    container_name: fishy-rag
    ports:
      - "8000:8000"
    env_file:
      - ./RAG/.env
    restart: unless-stopped